# Generated by Django 2.1.7 on 2019-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_column='First Name', max_length=45),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_column='Last Name', max_length=45),
        ),
    ]
