# Generated by Django 2.1.7 on 2019-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('fantasy_league_name', models.CharField(db_column='Fantasy_League_Name', max_length=45, primary_key=True, serialize=False)),
                ('goals_weight', models.DecimalField(db_column='Goals_Weight', decimal_places=1, default=3, max_digits=10)),
                ('assists_weight', models.DecimalField(db_column='Assists_Weight', decimal_places=1, default=2, max_digits=10)),
                ('powerplay_goals_weight', models.DecimalField(db_column='Powerplay_Goals_Weight', decimal_places=1, default=1, max_digits=10)),
                ('powerplay_points_weight', models.DecimalField(db_column='Powerplay_Points_Weight', decimal_places=1, default=1, max_digits=10)),
                ('shorthanded_goals_weight', models.DecimalField(db_column='Shorthanded_Goals_Weight', decimal_places=1, default=2, max_digits=10)),
                ('shorthanded_points_weight', models.DecimalField(db_column='Shorthanded_Points_Weight', decimal_places=1, default=1, max_digits=10)),
                ('plus_minus_weight', models.DecimalField(db_column='+/-_Weight', decimal_places=1, default=1, max_digits=10)),
                ('penalty_minutes_weight', models.DecimalField(db_column='Penalty_Minutes_Weight', decimal_places=1, default=0.5, max_digits=10)),
                ('game_winning_goals_weight', models.DecimalField(db_column='Game_Winning_Goals_Weight', decimal_places=1, default=1, max_digits=10)),
                ('shots_on_goal_weight', models.DecimalField(db_column='Shots_on_Goal_Weight', decimal_places=1, default=0.4, max_digits=10)),
                ('wins_weight', models.DecimalField(db_column='Wins_Weight', decimal_places=1, default=4, max_digits=10)),
                ('losses_weight', models.DecimalField(db_column='Losses_Weight', decimal_places=1, default=-2, max_digits=10)),
                ('overtime_losses_weight', models.DecimalField(db_column='Overtime_Losses_Weight', decimal_places=1, default=-2, max_digits=10)),
                ('shots_against_weight', models.DecimalField(db_column='Shots_Against_Weight', decimal_places=1, default=0.2, max_digits=10)),
                ('saves_weight', models.DecimalField(db_column='Saves_Weight', decimal_places=1, default=0.2, max_digits=10)),
                ('goals_against_weight', models.DecimalField(db_column='Goals_Against_Weight', decimal_places=1, default=-1, max_digits=10)),
                ('saves_percentage_weight', models.DecimalField(db_column='Saves_Percentage_Weight', decimal_places=1, default=0, max_digits=10)),
                ('goals_against_average_weight', models.DecimalField(db_column='Goals_Against_Average_Weight', decimal_places=1, default=0, max_digits=10)),
                ('shutouts_weight', models.DecimalField(db_column='Shutouts_Weight', decimal_places=1, default=2, max_digits=10)),
                ('maximum_number_of_players', models.IntegerField(db_column='Maximum_Number_of_Players', default=20)),
                ('minimum_number_of_goalies', models.IntegerField(db_column='Minimum_Number_of_Goalies', default=1)),
                ('minimum_number_of_defencemen', models.IntegerField(db_column='Minimum_Number_of_Defencemen', default=2)),
                ('minimum_number_of_right_wing', models.IntegerField(db_column='Minimum_Number_of_Right_Wing', default=1)),
                ('minimum_number_of_left_wing', models.IntegerField(db_column='Minimum_Number_of_Left_Wing', default=1)),
                ('minimum_number_of_center', models.IntegerField(db_column='Minimum_Number_of_Center', default=1)),
                ('fantasy_league_invite_code', models.CharField(db_column='Fantasy_League_Invite_Code', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'fantasy_league',
            },
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_team_name', models.CharField(db_column='Fantasy_Team_Name', max_length=45)),
                ('fantasy_points', models.IntegerField(db_column='Fantasy_Points', default=0)),
            ],
            options={
                'db_table': 'fantasy_team',
            },
        ),
        migrations.CreateModel(
            name='GoalieTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'goalie_teams',
            },
        ),
    ]
