# Generated by Django 2.1.7 on 2019-04-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyleague',
            name='goals_against_average_weight',
        ),
    ]
