# Generated by Django 2.1.7 on 2019-04-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalieteams',
            name='fantasy_league_name',
        ),
        migrations.RemoveField(
            model_name='skaterteams',
            name='fantasy_league_name',
        ),
    ]
