# Generated by Django 2.1.7 on 2019-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_auto_20190325_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyleague',
            name='assists_weight',
            field=models.DecimalField(db_column='Assists_Weight', decimal_places=0, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='game_winning_goals_weight',
            field=models.DecimalField(db_column='Game_Winning_Goals_Weight', decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='goals_against_average_weight',
            field=models.DecimalField(db_column='Goals_Against_Average_Weight', decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='goals_against_weight',
            field=models.DecimalField(db_column='Goals_Against_Weight', decimal_places=0, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='goals_weight',
            field=models.DecimalField(db_column='Goals_Weight', decimal_places=0, default=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='losses_weight',
            field=models.DecimalField(db_column='Losses_Weight', decimal_places=0, default=-2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='maximum_number_of_players',
            field=models.IntegerField(db_column='Maximum_Number_of_Players', default=20),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='minimum_number_of_center',
            field=models.IntegerField(db_column='Minimum_Number_of_Center', default=1),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='minimum_number_of_defencemen',
            field=models.IntegerField(db_column='Minimum_Number_of_Defencemen', default=2),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='minimum_number_of_goalies',
            field=models.IntegerField(db_column='Minimum_Number_of_Goalies', default=1),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='minimum_number_of_left_wing',
            field=models.IntegerField(db_column='Minimum_Number_of_Left_Wing', default=1),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='minimum_number_of_right_wing',
            field=models.IntegerField(db_column='Minimum_Number_of_Right_Wing', default=1),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='overtime_losses_weight',
            field=models.DecimalField(db_column='Overtime_Losses_Weight', decimal_places=0, default=-2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='penalty_minutes_weight',
            field=models.DecimalField(db_column='Penalty_Minutes_Weight', decimal_places=0, default=0.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='plus_minus',
            field=models.DecimalField(db_column='+/-_Weight', decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='powerplay_goals_weight',
            field=models.DecimalField(db_column='Powerplay_Goals_Weight', decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='saves_percentage_weight',
            field=models.DecimalField(db_column='Saves_Percentage_Weight', decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='saves_weight',
            field=models.DecimalField(db_column='Saves_Weight', decimal_places=0, default=0.2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='shorthanded_assists_weight',
            field=models.DecimalField(db_column='Shorthanded_Assists_Weight', decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='shorthanded_goals_weight',
            field=models.DecimalField(db_column='Shorthanded_Goals_Weight', decimal_places=0, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='shots_on_goal_weight',
            field=models.DecimalField(db_column='Shots_on_Goal_Weight', decimal_places=0, default=0.4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='shutouts_weight',
            field=models.DecimalField(db_column='Shutouts_Weight', decimal_places=0, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='wins_weight',
            field=models.DecimalField(db_column='Wins_Weight', decimal_places=0, default=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='losses',
            field=models.IntegerField(db_column='Losses', default=0),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='overtime_losses',
            field=models.IntegerField(db_column='Overtime_Losses', default=0),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='saves',
            field=models.IntegerField(db_column='Saves', default=0),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='shots_against',
            field=models.IntegerField(db_column='Shots_Against', default=0),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='shutouts',
            field=models.IntegerField(db_column='Shutouts', default=0),
        ),
        migrations.AlterField(
            model_name='nhlgoalies',
            name='wins',
            field=models.IntegerField(db_column='Wins', default=0),
        ),
        migrations.AlterField(
            model_name='nhlplayers',
            name='games_played',
            field=models.IntegerField(db_column='Games_Played', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='defencemen_flag',
            field=models.IntegerField(db_column='Defencemen_Flag'),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='game_winning_goals',
            field=models.IntegerField(db_column='Game_Winning_Goals', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='goals',
            field=models.IntegerField(db_column='Goals', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='penalty_minutes',
            field=models.IntegerField(db_column='Penalty_Minutes', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='plus_minus',
            field=models.IntegerField(db_column='+/-', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='powerplay_goals',
            field=models.IntegerField(db_column='Powerplay_Goals', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='powerplay_points',
            field=models.IntegerField(db_column='Powerplay_Points', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='shorthanded_goals',
            field=models.IntegerField(db_column='Shorthanded_Goals', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='shorthanded_points',
            field=models.IntegerField(db_column='Shorthanded_Points', default=0),
        ),
        migrations.AlterField(
            model_name='nhlskaters',
            name='shots_on_goal',
            field=models.IntegerField(db_column='Shots_on_Goal', default=0),
        ),
    ]
